DataDog/agent-linux-install-script

CHANGELOG.rst
install_script.sh.template

Preps for 0.12.0 release of the install script.

[release] add changelog entries + bump template version

---

install_script.sh.template
test/dockertest.sh
test/localtest.sh

Added an option to install system-probe (using default configuration) via environment variable `DD_SYSTEM_PROBE_ENSURE_CONFIG=true`

Added system-probe installation using

---

CHANGELOG.rst
install_script.sh.template

Release of version 1.16 waiting for #30 to get QA before merge

Release version 1.16

---

CHANGELOG.rst
install_script.sh.template

Release new version of install script

Release of version 1.17

---

Makefile

Add a list of commits from the previous tag to the changelog in the make targets.
I already filtered some commits that might be useless (related to releasing)
I'm not a big expert of Makefiles so my code looks dirty to me, don't hesitate to give feedback/recommendations

Add commits in the changelog to help its generation

---

install_script.sh.template

This fixes a systematic warning for all APT search operations run by the user

Fix datadog.list permissions

---

install_script.sh.template

Ruby package to be released to prod imminently

Add ruby to list of apm libraries

---

.gitignore
.gitlab-ci.yml
Makefile
install_script.sh.template
test/localtest.sh

This PR adds a new script `install_script_docker_injection.sh` which sets `DD_APM_INSTRUMENTATION_ENABLED="docker"` in all cases.

Add a new install_script_docker_injection script

---

README.md

Harmless PR to test [devflow](https://datadoghq.atlassian.net/l/cp/RSjknqPQ) keywords

Update readme for devflow tests

---

.gitlab-ci.yml
test/e2e/common.go
test/e2e/upgrade_5_test.go
test/e2e/upgrade_6_test.go
test/e2e/upgrade_7_test.go

[e2e] part 3: extract one test per mode

---

test/e2e/install_fips_test.go

Add tests for fips mode, based on https://docs.google.com/document/d/1W3nkxIS-6ltTo5CopRyNDcBJd9WWYNG-v9N2nd3y75E/edit#heading=h.wj9riz2hijyt

[e2e] part 4: add fips test

---

test/e2e/install_maximal_and_replay_test.go

Add install test with max number of environment variables plus retry install, based on https://docs.google.com/document/d/1W3nkxIS-6ltTo5CopRyNDcBJd9WWYNG-v9N2nd3y75E/edit#heading=h.wj9riz2hijyt

[e2e] part 5 add install max test

---

.gitlab-ci.yml
test/e2e/common.go
test/e2e/install_fips_test.go
test/e2e/install_maximal_and_replay_test.go
test/e2e/install_test.go
test/e2e/upgrade_5_test.go
test/e2e/upgrade_6_test.go
test/e2e/upgrade_7_test.go

Forgot to pass the platform parameter to the EC2 VM options 🤦‍♀️

[e2e] 🐛 actually run e2e on expected platform

---

install_script.sh.template
test/localtest.sh
unit_tests/test_install_script.sh

File creation behaviour was slightly changed by #50 
This PR reverts to the previous mechanism

prevent file creation based on input variable

---

CHANGELOG.rst
install_script.sh.template
install_script_op_worker1.sh
install_script_op_worker2.sh

1.31.0
- (fleet) improve the installer install script (#182)
- (fleet) Add a 20s timeout on telemetry uploads (#181)

Linux Install Script release 1.31.0

---

install_script.sh.template

Second step of https://github.com/DataDog/agent-linux-install-script/pull/186.

(fleet) rollout to us5

---

CHANGELOG.rst
install_script.sh.template
install_script_op_worker1.sh
install_script_op_worker2.sh

1.31.2
- (fleet) rollout to us5 (#190)

Install script release 1.31.2

---

install_script.sh.template

Rollout started in https://github.com/DataDog/agent-linux-install-script/pull/186.

(fleet) installer rollout to ap1 & eu1

---

CHANGELOG.rst
install_script.sh.template
install_script_op_worker1.sh
install_script_op_worker2.sh

1.31.3
- (fleet) installer rollout to ap1 & eu1 (#194)

Install script release 1.31.3

---

CHANGELOG.rst
install_script.sh.template
install_script_op_worker1.sh
install_script_op_worker2.sh

1.31.4
- (fleet) finish rollout of the installer (#198)

install script release 1.31.4

---

install_script.sh.template

Finish migration of installer

---

CHANGELOG.rst
install_script.sh.template
install_script_op_worker1.sh
install_script_op_worker2.sh

1.31.6
- Update install_script.sh.template (#204)

install script release 1.31.6

---

install_script.sh.template

This PR populates the config with the installer registry parameters

(fleet) populate the config with the installer registry parameters

---

.gitlab-ci.yml

https://github.com/DataDog/datadog-agent/pull/27625
#incident-28954

Rotate install script api key

---

install_script.sh.template

Similar to https://github.com/DataDog/datadog-agent/pull/28158

[Documentation] Fix link to in-app installation page

---

install_script.sh.template

Add the `remote_policies` config entry for Fleet's policies

(fleet) add remote policies config

---

install_script.sh.template

Add back support for APM SSI centos6

Add back support for APM SSI centos6

---

install_script.sh.template

Fixes error such as `bash: line 1288: /tmp/ddog_install_error_msg: Permission denied`

ensure we can write to the log files

---

test/e2e/common.go

Check for errors while copying scripts so that we fail early.  Also announce the step since there could be a pause there.

[e2e] Check for errors while copying scripts

---

install_script.sh.template
unit_tests/test_install_script.sh

It's been replace by stable config.

Remove usage of /etc/environment for app sec and profiling

---

.gitlab-ci.yml

Update artifact path after https://github.com/DataDog/datadog-agent/pull/38191 is merged

Update target version after change to testing artifacts upload
