DataDog/agent-linux-install-script

- Makefile
- install_script.sh.template
- test/localtest.sh
We don't want to show the warning on the versioned scripts, as they represent explicit version choice.
NOTE: This also means that installing IoT Agent or Dogstatsd will no longer be possible with `install_script_agent6.sh` (unless `DD_AGENT_MAJOR_VERSION=7` is specified explicitly), but I think that's ok.
> Remove DD_AGENT_MAJOR_VERSION warning on versioned scripts

- .gitlab-ci.yml
Debian 8 signing keys have expired, but Ubuntu 14 will still be maintained until April 2024. From our perspective these two systems are same.
> Move from Debian 8 to Ubuntu 14 in CI

- .gitlab-ci.yml
- install_script.sh.template
- test/dockertest.sh
This PR adds a few changes to the script to better tackle the installation of the FIPS proxy. 
Specifically it improves a little bit the management of the FIPS proxy side of things, and also adds some config and service management steps to fully enable the services. 
It also addresses two minor issues:
- `dockertest.sh` script platform definition support
- updated buildimages tag
> [template] fips-proxy package updates

- install_script.sh.template
This PR add success and failure telemetry events for agent installation. There are 3 main changes:
1.  The `report_telemetry()` function that sends telemetry to the backend
2. Calling `report_telemetry()` in every case there was an `exit`. This consists of:
a. Setting `ERROR_MESSAGE`
b. Setting `ERROR_CODE`
c. Printing the message to the screen
d. Reporting telemetry
3. Setting `report_failure_url` and `telemetry_url` was moved to earlier in the script to catch more potential errors.
It was not possible to test every scenario, but I manually tested the following using the production telemetry intake:
* Successful install
* Successful upgrade
* Failure because of unknown minor revision (set via environment variable)
* Failure because of unknown flavor (set via environment variable)
* …
> Add success and failure telemetry events

- install_script.sh.template
This PR does 2 things:
- It prevents from installing the FIPS proxy if the Agent minor version is lower than 41 or when the architecture is not x86_64
- We do this because the `fips` option as been added in `7.41` and the FIPS proxy is not supported for versions older than 7.41
- It adds `fips` configuration into `datadog.yaml` instead of the bunch of `dd_url` options
- I used `report_telemetry` to follow the pattern but I'm not really sure if this error is relevant for the instrumentation-telemetry team tbh (We don't except this error to be triggered a lot anyway)
-  Right now `ARM64` arch is not supported for FIPS proxy. The current error is 'no package was found' but should we add a more explicit message ? 
- `agent_minor_version_without_patch` value still contains patch information if …
> Use `fips` option instead of hardcoded *dd_url when DD_FIPS_MODE is set

- Makefile
To automate the install script release process we need two new targets that :
- Updates the changelog and bumps the version (before the release)
- Updates the changelog again and adds the .post suffix to the version (after the release)
- Added target pre_release_\<new-version\> : 
-  Updates install_script_version=\<new-version\> in install_script.sh.template. It removes the .post as well
- Updates the CHANGELOG.rst that renames the Unreleased version on top to \<new-version\>
- Added target post_release_\<new-version\>:
- Updates install_script_version=\<new-version\> in install_script.sh.template to install_script_version=\<new-version\>.post (adding the .post at the end).
- Updates the CHANGELOG.rst by adding a new Unreleased "version" on top of the file.
> Makefile targets to automate the release process

- install_script.sh.template
+ Previous implementation was making impossible to install a pre-release version. This should fix it and still parse pre-release correctly.
+ Fix on error handling that didn't worked on certain/older shell : 
```
agent_minor_version=19.0 
if [[ "$agent_minor_version" -lt 35 ]]; then
echo ERROR
else
echo OK
fi
```
On classic recent shell we get
```
ERROR
```
but on more basic shell like `sh` we get 
```
sh: [[: 19.0: syntax error: invalid arithmetic operator (error token is ".0")
OK
```
Test the script with : 
- A release version ( e.g : 7.43.0 )
- A pre-release version ( e.g : 7.15.1~beta.1 )
- An error case ( e.g : datadog-dogstatsd 7.19.0~rc.7 on aarch64. Expected output : ``The Datadog Dogstatsd is only available since version 7.35.0 for your architecture.``)
> Fix pre-release handing

- install_script.sh.template
- Renamed ``REPO_URL`` to ``DD_REPO_URL``
- ``REPO_URL`` is still working because of retro-compatibility concern but a deprecation warning is printed as well.
> Rename REPO_URL to DD_REPO_URL.

- test/localtest.sh
- Ubuntu 14 tests didn't trigger an error when ``EXPECTED_MINOR_VERSION != MINOR_VERSION``. Previously we used ``-ne`` in the condition. But in the case where ``MINOR_VERSION`` is empty, ``test $VERSION -ne $EMPTY_VERSION`` would result in an error returning false. Meaning that it wouldn't enter the if that was supposed to handle error and be considered as valid when it wasn't. That's why ``-ne`` has been replaced with ``!=`` that handle the comparaison as string so even empty string would trigger the error.
- ``MINOR_VERSION`` is empty because ubuntu 14's dpkg-query version is 1.17.x which is inferior of 1.18.16 needed to use the format ``Upstream-Version``. Instead we manually parse the version manually with ``sed``
> [Fix] Ubuntu 14 false positive tests fix + dpkg-query upstream version equivalent

- install_script.sh.template
In order to upgrade the Agent by rerunning the install script when dnf is used, we have to correctly detect it on all distros where it exists.
> Use dnf's --best on all distros that have dnf

- install_script.sh.template
Noticed a usage where the mapping fails because the flavor also comes from hardcoded data inside the script (lines 489, 495, 507)
```shell
/usr/bin/systemctl
* Starting the Unknown...
Your Unknown is running and functioning properly.
```
Restore usage of underscores in options as it would require change at all those places and would probably bring confusion
> Use dash for options

- install_script.sh.template
To prepare 2024 key rotation, we add the new signature keys for APT and RPM repositories
> Add new APT and RPM signing keys

- install_script.sh.template
Fix an issue reported via a support card about the install script not working on ubuntu while another process is using dpkg.
> [install_script] Unable to acquire the dpkg frontend lock when multiple instance of dpkg are running

- install_script.sh.template
Following #57, one ``apt-get install`` line is getting error suppressed when it shouldn't.
> Small fix to error handling while retrying dpkg lock issues

- Makefile
sed -i "" gets rejected by GNU sed as it tries to interpret "" as a path
> Makefile: fix in place sed on linux

- Makefile
This rule will ensure we are in a correct setup to create a tag and will ensure all tags are signed and annotated
> Makefile: add a 'tag' rule

- Makefile
A makefile conditional can't be indented with tags, so this PR indents the conditional with spaces.
It also adds a missing phony target.
I probably changed something in my editor config and wrecked the tag rule after testing it, sorry about that.
> Fix conditional & add phony targets

- install_script_op_worker1.sh
- test/dockertest.sh
- Fix conditionals for the ENTRYPOINT_PATH
- Correct the opw source to update
The entrypoint path was checking environment variables for presence, rather than true/false - while CI would always set a value for agent CI.
The op worker install script had updated the source file name, but failed to update the apt-get update command
amazonlinux:2023 was included in the op worker test matrix, but wasn't yet mirrored - this was resolved in https://github.com/DataDog/images/pull/4228
> Fix linux installer scripts

- install_script.sh.template
This variable immediately gets overwritten, seemingly a missed bit of code from an older refactor.
> Remove unused gpgkeys variable

- install_script.sh.template
This PR cleans up a few things in the script template:
- use `if [ -n "$FOO" ]` instead of `if [ foo ]`
- Remove an unneeded `$(echo foo)` to display `$foo`
- Use `$()` instead of backticks, as advised by shellcheck
> Minor cleanup in script template

- .gitlab-ci.yml
- test/dockertest.sh
- test/old-suse-startup.sh
Migrated the previous image using an opensuse 13.2 with bash 3 downgraded using external dependency into an internal docker image getting rid of the external dependency.
> [SLES11] migrating tests using third party dependency to internal image

- .gitlab-ci.yml
Create a separate job for opensuse13 tests.
We do not want it to be triggered by datadog-agent pipeline since opensuse 13 support the agent up to the version 6.32
> Use dedicated jobs for opensuse13 that are not launched on pipeline trigged from datadog-agent

- install_script.sh.template
Arm was not supported for FIPS Proxy so a warning was added in #22.
We'll be releasing ARM packages in the next few weeks so we can include it in the install script.
> Allow installation of arm64 FIPS Proxy packages

- install_script.sh.template
Grep specific part of the system's package manager error output to display them at the end to increase visibility when an installation fails because of insufficient available space.
> Show error summary when installation fails because of insufficient available disk space

- CHANGELOG.rst
- install_script.sh.template
- install_script_op_worker1.sh
New release for fips proxy
QA test:
```
inv create-vm --no-install-agent -r arm64
```
then
```
ubuntu@ip-10-1-59-175:~$ uname -m
aarch64
ubuntu@ip-10-1-59-175:~$ DD_API_KEY=XXX DD_FIPS_MODE="True" DD_SITE="datadoghq.com" DD_APM_INSTRUMENTATION_ENABLED=host bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh)"
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 45377  100 45377    0     0   391k      0 --:--:-- --:--:-- --:--:--  392k
* Datadog Agent 7 install script v1.21.0
FIPS mode isn't available for your architecture
Unable to send telemetry
```
then with modified script
```
ubuntu@ip-10-1-59-175:~$ DD_API_KEY=XXX DD_FIPS_MODE="True" DD_SITE="datadoghq.com" …
```
> Prepare release 1.22.0

- .gitlab-ci.yml
- install_script_vector0.sh
- test/dockertest.sh
- test/vector-test.sh
Opened as an alternative to https://github.com/vectordotdev/vector/pull/18777
This struck me as a better location to maintain the script as AP is likely to be responsible for it as it is for the Agent and OPW scripts. Additionally since the scripts are so ~~copied~~ related co-locating them seems sensible.
[Original PR](https://github.com/vectordotdev/vector/pull/18777)
> feat: Add install script for Vector

- test/e2e/agentflavor.go
- test/e2e/common.go
- test/e2e/doc.go
- test/e2e/install_test.go
Refactoring previous PR that added e2e tests for the installer script.
In this iteration no feature is added, only refactoring code to move common code.
Best reviewed per commit to follow the refactoring.
Next iteration will add one file per mode, and will add two new modes: fips and maximal install, with different assertions - you can see the next iteration in https://github.com/DataDog/agent-linux-install-script/pull/98/files#diff-89059d4760ebc9a893c31db5ec0d36a1305d6e1d82ad43b4d8331e97b8e6552b
> [e2e] part 2 refactoring

- install_script.sh.template
If we use the install_script with `DD_NO_AGENT_INSTALL=true` you will face an error in RHEL systems:
```
yum install: error: the following arguments are required: PACKAGE
Updating Subscription Management repositories.
Unable to read consumer identity
```
This issue do not exist in APT-like systems because we install `datadog-signing-keys` at bare minimum
> Prevent errors when trying to install with no_agent in RHEL OS

- install_script.sh.template
- test/localtest.sh
Do not use datadog-apm-library-all to install every tracing library, because it doesn't allow us to easily force an upgrade to the latest version.
> remove datadog-apm-library-all

- .gitlab-ci.yml
- test/localtest.sh
By using a more compacted form it will be easier to add more dimensions to those matrices later on.
More specifically, in order to migrate to k8s we'd ideally need to have a single job per major version as we won't be able to start containers from the job, which will require a new matrix entry.
> CI: simplify test matrices

- CHANGELOG.rst
- install_script.sh.template
- install_script_op_worker1.sh
Reverts DataDog/agent-linux-install-script#115
Since we will do the release only after the freeze, let's revert this one for now
> Revert "Prepare 1.24.0 release"

- .gitlab-ci.yml
- test/dockertest.sh
This allows for a single job to run as part of `.test::script` which makes to migration to k8s runners possible
This needs https://github.com/DataDog/datadog-agent/pull/21000 on the `datadog-agent` repo side to ensure we don't break pipelines triggered from there
> CI: move major version in the test matrix

- test/dockertest.sh
While this made sense in the context of the CI, it impeeds the developers ability to run tests locally on a docker container
> dockertest.sh: revert parameters removal

- .gitlab-ci.yml
We will soon stop using dockertest.sh as part of the CI, but still need a way to provide our test parameters.
This PR provides those through environment variable that match what dockertest.sh does, and what the install script expect.
> CI: pass parameters as environment variables

- .gitlab-ci.yml
This handling needs to be done for all jobs, not only the one for the datadog-agent test.
> CI: move datadog-agent variable handling to a common before_script

- .gitlab-ci.yml
When the pipeline is triggered from another project, we don't include the MAJOR_VERSION from the test matrices, which cause the repo URL to be incorrect and the install to fail
> CI: provide a default value for MAJOR_VERSION

- .gitlab-ci.yml
Replicate what's done for OPW tests.
The intent is to stop running APM tests when triggering an install-script pipeline from the datadog-agent pipeline. These triggered pipeline use a specific testing repository which doesn't contain any APM binary, which causes the tests to fail
> CI: only run APM tests on push

- install_script.sh.template
- test/e2e/install_maximal_and_replay_test.go
- unit_tests/test_install_script.sh
Restore the previous behaviour, pseudo-code:
```
if DD_RUNTIME_SECURITY_CONFIG_ENABLED
create both files if they don't already exist
update security config in both files
if DD_COMPLIANCE_CONFIG_ENABLED
create security file if it doesn't already exist
update compliance config on it
```
This was changed to take benefit of `ensure_config_file_exist` and have testable methods
> Ensure correct behaviour with security_agent and system_probe configuration files

- README.md
- install_script.sh.template
Added information about the install script configuration:
- Raised the behaviour with respect to existing configuration file
- Split options in 2 categories: for agent configuration and for install script itself. The latter ones should not be used by customer.
- Documented each option
- I mentioned OPW and vector install script but didn't gave much details.
You can review the README [here](https://github.com/DataDog/agent-linux-install-script/blob/nschweitzer/APL-1981/documentation/README.md) for more comfort.
This README will eventually be referenced from [Agent Install Instruction page](https://app.datadoghq.com/account/settings/agent/latest?platform=debian).
> feat(documentation): Add information about the configuration options of install script

- test/e2e/common.go
- test/e2e/go.mod
- test/e2e/go.sum
Add the `getLatestEmbeddedPythonPath` function to fetch the path to the latest python version embedded into an agent
> [E2E] Install script e2e tests are fetching the latest available python version

- install_script.sh.template
- install_script_op_worker1.sh
- install_script_vector0.sh
Add options in curl and APT to have more resilience in install_script.
`yum` as a [default retry to 10](https://github.com/Distrotech/yum/blob/f4e54aeed297158c563828aa3ebb93d0c8ce7e38/docs/yum.conf.5#L364-L366) and [no option exist yet](https://github.com/openSUSE/zypper/issues/420) in zypper
> Enforce retries in install_script for curl calls

- .gitlab-ci.yml
I tested the invalidation in another [testing branch](https://github.com/DataDog/agent-linux-install-script/compare/slavek.kabrda/test-cf-invalidate?expand=1) (because the only way to test it fully would be to do an actual release).
> Invalidate install.datadoghq.com distribution on script release

- .gitlab-ci.yml
- install_script_op_worker1.sh
- install_script_op_worker2.sh
In OP / OPW 2.0 we will no longer support local pipeline configurations- remote configuration is the default. As such, the logic around remote configuration env vars and local pipelines needs to be removed from the install script.
https://datadoghq.atlassian.net/browse/OPA-1090
> Add install script for OPW v2

- .gitlab-ci.yml
I also don't see a _huge_ issue tracking `latest` here, and it would save us from having to update this regularly.
ref: https://github.com/DataDog/agent-linux-install-script/pull/24
> chore: Update buildimages tag

- Makefile
- install_script_op_worker2.sh
- **fix: Add op_worker2 script to Makefile release targets**
- **fix: Update op_worker2 metadata**
These two places were missed when the v2 script was added recently.
> fix: Update makefile and script metadata

- .gitlab-ci.yml
- install_script.sh.template
This will:
* Only allow installing pinned versions <= 6/7.51 on CentOS/RHEL 6
* Install 6/7.51 when performing an "unpinned" installation.
> Don't allow installing Agent > 6/7.51 on CentOS 6

- install_script.sh.template
`install.json` is not necessarily world-readable at this point (e.g. when we're upgrading from Agent 5). When the script is executed as non-root user, reading the install.json file will fail. This PR fixes it by adding the `sudo_cmd`.
> Use sudo for any operations with install.json

- install_script.sh.template
The ubuntu tests failed as systemd units entered a failed state due to missing datadog.yaml. Having a datadog.yaml before installing the updater is necessary to ensure that the updater knows what to install.
Customers can set rules such as: install agent version 7.51 on env prod
Fixes
Create an early datadog.yaml in the case of the updater
Ignore services restart on updater installation
> [BARX-289] fix updater ubuntu test + bootstrap config

- README.md
I noticed the README suggested that all of the script options were for internal testing purposes only, however this is not the case. We have a number of variables prefixed with `TESTING_` which are (almost) exclusively used in our testing internally, however several of the listed variables can/should be used by customers (to pin the minor version when installing, for example).
> chore: Clarify usage of script configuration options

- install_script.sh.template
We've been having some flakes on e2e tests for the install script ([example](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/488660351#L1035)).
The culprit seems to be related failure during autorefresh when installing. Adding `--no-refresh` should prevent the autorefresh from happening, removing that chance of error. I didn't add the `--no-refresh` to `install curl` since the autorefresh may be useful there and it's only done when curl doesn't already exist which is probably not very typical.
Official docs for this option under https://en.opensuse.org/SDB:Zypper_manual#GLOBAL_OPTIONS.
> Add --no-refresh to zypper invocations

- install_script_op_worker2.sh
During OP 2.0 development in Q1 2024 we added a number of env vars that need to be supported in the install script.
This is a first pass hard coded solution.
> Add missing env vars to OP 2.0 script

- install_script.sh.template
- test/e2e/install_test.go
Reverts DataDog/agent-linux-install-script#174
> Revert "Install Old 2022 RPM GPG key only when needed for agent <= 7.35"

- .gitlab-ci.yml
- install_script.sh.template
- add the new boostrap call
- remove the on-disk installer file
- add support for RPM
- setting DD_INSTALLER will always install, regardless of APM being enabled
- add `DD_REMOTE_UPDATES`
> (fleet) improve the installer install script

- install_script.sh.template
First step of the migration to the installer for [APM single step](https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/single-step-apm/?tab=linuxhostorvm) beta customers.
The installer will gradually replace the installation of deb/rpm packages for APM's injector and libraries.
> (fleet) enable installer on us3 for APM single step beta customers

- install_script.sh.template
Reduce the deployment of the installer in https://github.com/DataDog/agent-linux-install-script/pull/186 to only debian/ubuntu  users.
> (fleet) scope to debian

- CHANGELOG.rst
- install_script.sh.template
- install_script_op_worker1.sh
- install_script_op_worker2.sh
1.31.1
- (fleet) scope to debian (#188)
- (fleet) enable installer on us3 for APM single step beta customers (#186)
> Linux Install script release 1.31.1

- test/e2e/install_test.go
integrations metadata expired since First May 2024 for 7.42.0 and needs to be disabled
Left as comment for now, might replace the test later with another test with `--unsafe-disable-verification` since we're pinning to the very first version of the package
> [E2E] Disable extraintegration check on pinned version agent

- install_script.sh.template
Second phase after https://github.com/DataDog/agent-linux-install-script/pull/186. Rolling out the RPM of the installer.
> (fleet) installer RPM rollout

- install_script.sh.template
- test/e2e/install_installer_test.go
This PR:
- Moves the installation of the installer at the top after input resolution
- Adds a way to check if a package is installed by the installer
- Filter out packages installed by the installer when installing package manager packages
- Avoid running the setup script of the injector if its installed with the installer
> (fleet) filter out packages installed by the installer

- install_script.sh.template
Installation was already broken because the installer is linked to a newer version of libc, but we want to exit early rather than installing broken packages.
> Add a check to forbid APM injection installation on redhat 6

- install_script.sh.template
This PR adds the installer service to the services to restart after the config has been populated.
> (fleet) restart the installer service when remote updates are enabled

- .gitlab-ci.yml
- install_script.sh.template
- test/e2e/install_installer_test.go
[link to updater suite test on suse](https://gitlab.ddbuild.io/DataDog/agent-linux-install-script/-/jobs/526109037)
Removed e2e `allow_failure: true` to properly catch failing tests. They could fail silently and be picked only at release time, as releases enforce that all tests must pass.
> (fleet) add suse support

- install_script.sh.template
Fixes `Unknown` logs for datadog-installer
> fix unknown

- .gitlab-ci.yml
Copied [definition](https://github.com/DataDog/datadog-agent/blob/main/.gitlab-ci.yml#L48C1-L57C31) from `datadog-agent`, this should reduce instabilities, especially `runner-system-failure` like [here](https://gitlab.ddbuild.io/DataDog/agent-linux-install-script/-/jobs/533660409)
> feat(ci): Add default retry for infra failures

- install_script.sh.template
- unit_tests/test_install_script.sh
Adds support for handling `DD_PROFILING_ENABLED` in a similar vein to how `DD_IAST_ENABLED` and `DD_APPSEC_ENABLED` are propagated to `/etc/environment` in #157.
We want to get some customers on a private beta of profiling with SSI.
Unit test added and confirmed to work with
```
make
python3 unit_tests/extract_functions.py
sudo ./unit_tests/test_install_script.sh
```
> PROF-9889: Add support for propagating DD_PROFILING_ENABLED

- install_script.sh.template
WIth the 2024 GPG key rotation ongoing customer will need to start trusting a new future GPG key that will be used in 2028.
> [2024 GPG Key Rotation] Import new GPG future key

- install_script.sh.template
Fixes a bug in #220 where echo was incorrectly used with sudo to create `/etc/environment` when it doesn't exist.
> PROF-9889: Fix for permission denied on empty /etc/environment

- .github/CODEOWNERS
This PR updates the codeowners to the updated team name Agent Delivery
> chore(codeowners): update barx to agent-delivery

- install_script.sh.template
- test/localtest.sh
Today on an Debian-like OS, when a tracer version is pinned, it's excluded from APT updates regardless of whether it has been installed or not. It worked fine before as it was always installed through APT, but now it can and will be installed with the installer by default: running apt-mark will fail the install script.
This PR fixes it by checking that the tracer has been installed through APT before running apt-mark. It also fixes injection tests.
> fix(debian): Only exclude pinned tracer versions from apt updates if they've been installed

- install_script.sh.template
There was no environment variable passed to the `is-installed` operation, which meant:
- A warning log about no telemetry was emitted per package check
- No telemetry on is-installed
This PR fixes both by adding the telemetry environment variables to the is-installed operation
> upgrade(installer): Add telemetry on is-installed operation

- install_script.sh.template
The current log message isn't clear and sounds like the package wasn't installed at all
> fix(logs): Make installer log more understandable

- install_script.sh.template
When installing the agent with the installer, the install info is set [here](https://github.com/DataDog/datadog-agent/blob/1d08a6a9783fe271ea3813ddf9abf60244abdf2c/pkg/fleet/installer/service/datadog_agent.go#L106-L108).
Today it's overridden later on in the install script: this PR fixes it.
> fix(installer): Don't override installer install_info

- .gitlab-ci.yml
At some point, the passing of the flavor to the bash-based tests was lost and we're installing the same datadog-agent in all testing jobs.
This fixes that by passing the necessary environment variable. It also separates Agent 6 jobs into a separate set of jobs, because:
- It doesn't make sense to test Agent 6 on "alternative flavors", the test script will just simply pass without doing anything, which is a bit unnecessary (why spin up a bunch of runners just to do nothing).
- As we're no longer releasing Agent 6 from datadog-agent's main, this separation can be a first step towards adding some rule to not trigger Agent 6 tests when not applicable.
The regression was probably introduced in https://github.com/DataDog/agent-linux-install-script/pull/121.
> Pass flavor to tests

- .gitlab-ci.yml
Does the same kind of prefetching that we do on datadog-agent (the code was based on that, see[here](https://github.com/DataDog/datadog-agent/blob/d8d7237a184c548addc47effa592e236d0c3ae95/.gitlab/deps_fetch/deps_fetch.yml#L78) and [here](https://github.com/DataDog/datadog-agent/blob/d8d7237a184c548addc47effa592e236d0c3ae95/.gitlab/deps_fetch/deps_fetch.yml#L14), except here we don't have invoke tasks here).
> Prefetch go dependencies

- install_script.sh.template
This PR should fix the following:
```
Stopping service datadog-agent that was launched during the package installation.
[539](https://gitlab.ddbuild.io/DataDog/agent-linux-install-script/-/jobs/598331734#L539)        bash: line 1964: sudo systemctl stop datadog-agent-process: command not found
[540](https://gitlab.ddbuild.io/DataDog/agent-linux-install-script/-/jobs/598331734#L540)        bash: line 1965: sudo systemctl stop datadog-agent-sysprobe: command not found
[541](https://gitlab.ddbuild.io/DataDog/agent-linux-install-script/-/jobs/598331734#L541)        bash: line 1966: sudo systemctl stop datadog-agent-trace: command not found
[542](https://gitlab.ddbuild.io/DataDog/agent-linux-install-script/-/jobs/598331734#L542)        bash: line 1967: sudo systemctl stop …
```
> fix(install-script): fix stop instructions not being ran properly when DD_INSTALL_ONLY is set

- .github/workflows/slapr.yml
[JIRA-510](https://datadoghq.atlassian.net/browse/BARX-510)
Github token permissions should follow the [least privilege principle](https://datadoghq.atlassian.net/wiki/x/TIVE6Q)
Reset workflow permissions to validate we can enable `read-only` default permissions at repository level to provide a strong baseline protection measure
[JIRA-510]: https://datadoghq.atlassian.net/browse/JIRA-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(github): reduce workflow token permission

- .gitlab-ci.yml
Test reporting is currently broken as test artifacts are overwritten on retries, as we store them by job name instead of by job id. This PR should fix it.
> [gitlab] store test results artifacts by job id instead of by job name

- test/e2e/common.go
The `DD_INSTALL_ONLY` test is still flaky on redhat 8 https://gitlab.ddbuild.io/DataDog/agent-linux-install-script/-/jobs/611768206.
It is still unclear why and very difficult to reproduce. I propose to:
- Check that `datadog-agent-process` and `datadog-agent-trace` are also inactive (they can be started during the `dnf install` or `apt-get install`)
- Dump `journalctl` on test failure.
> Check that trace and process services are stopped as well

- .gitlab-ci.yml
This PR modifies the gitlab configuration of `e2e_test_upload` to always run after `e2e`
> [gitlab] always upload test results

- install_script.sh.template
Installation of APM libraries requires re-running the install script.
This PR allows installing APM libraries without updating the agent or an involved step to avoid an update (fetch the already installed version and pin Major + Minor parameters)
> Allow apm install without updating the agent

- install_script.sh.template
This dependency appears to cause issues on some systems where `systemd` is held. 
Since this dependency is only a transitive dependency starting from apt 1.5, we don't need it then
> don't attempt to install apt-transport-https with APT >= 1.5.0

- install_script.sh.template
It is spelled as 2 words in the files we inspect to determine the distribution we're running on.
Fixing the search pattern changes the value assigned to DISTRIBUTION so all existing checks have been updated.
OS value was also update for consistency, so we don't have to wonder if we need to spell Red Hat as one or two words
Before this change, `DISTRIBUTION` is set to `Linux` on Red Hat, which circumvents the check to ensure we pin the version to `7.51.x` on RHEL 6
> Fix Red Hat detection

- .gitlab-ci.yml
This also removes the duplicated `retry` option set on the .test job.
[Example of failure](https://gitlab.ddbuild.io/DataDog/agent-linux-install-script/-/pipelines/45527302) as I remove Agent 6 jobs from `datadog-agent`
> chore: [BARX-576] Don't run test_agent6 jobs from datadog-agent pipelines

- install_script.sh.template
This PR fixes the forwarding of the network metadata. We're hitting some issues with `.` that are interpreted in domain names. Replacing those by `_` to fix the issue.
> (fleet) fix network telemetry

- .gitlab-ci.yml
Rename buildimages variables to stick to new names set in `datadog-agent` repository (needs https://github.com/DataDog/datadog-agent/pull/30380)
Took the opportunity to bump the image version used
> ci(buildimages): Rename buildimages

- .gitlab-ci.yml
Update to new image version. We can now pull from `registry.ddbuild.io`
> [ACIX-322] Use registry.ddbuild.io for buildimages

- install_script.sh.template
`tee` writes not only to the file but also to stdout making the telemetry installation trace print
redirecting tee to /dev/null is a[ pattern already followed in install script ](https://github.com/DataDog/agent-linux-install-script/blob/main/install_script.sh.template#L1794)
This log was introduced by [mistake here
](https://github.com/DataDog/agent-linux-install-script/pull/289/files)
logs obtained after fix
```
Ign:1 https://apt.datadoghq.com stable InRelease
Hit:2 https://apt.datadoghq.com stable Release
Reading package lists...
Installing package(s): datadog-signing-keys
```
logs before fix
```
gpg: key D3A80E30382E94DE: "Datadog, Inc <package@datadoghq.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Ign:1 https://apt.datadoghq.com stable InRelease …
```
> fix noisy debug log

- .gitlab-ci.yml
- install_script.sh.template
APM package installation has been completed by datadog-installer since June 2024 and are distributed through in OCIs through container-registries. Deb/Rpm packages were left as fallback while we gain confidence on the installation.
Removing the fallback now
Deb/Rpm versions are also quite old now and shouldn't be installed anymore
> remove apm deb/rpm

- Makefile
- test/localtest.sh
The test suite `install_script_docker_injection.sh` was failing as DD_APM_INSTRUMENTATION_ENABLED="docker" is expected to be propagated, yet the template just sets it a local var. Making datadog-installer miss the env
It's not a scenario expected in customer environments as setting `DD_APM_INSTRUMENTATION_ENABLED="docker"` is always documented and we document the general `install_script.sh`
I'll discard `install_script_docker_injection.sh` after next release as its not supported for the GA. Making sure first with another release that the env is properly set
> Tests to ensure that deb/rpm are not installed

- install_script.sh.template
APM package installation has been completed by datadog-installer since June 2024 and are distributed through in OCIs through container-registries. Deb/Rpm packages were left as fallback while we gain confidence on the installation.
Removing the fallback now
Deb/Rpm versions are also quite old now and shouldn't be installed anymore
This is the 2nd run of this change as the [previous was mistakenly merged while iterating on a review](https://github.com/DataDog/agent-linux-install-script/pull/294)
Updates to [make tests pass have been addressed in this PR](https://github.com/DataDog/agent-linux-install-script/pull/299)
> remove apm deb/rpm v2

- install_script.sh.template
https://github.com/DataDog/agent-linux-install-script/blob/c5be00b265e2e7e4646b07161ad955dba729409b/install_script.sh.template#L273-L301
-> When encountering a key not in the mapping, we default to `Unknown`, so we can never hit the exit block which looks for an empty string: https://github.com/DataDog/agent-linux-install-script/blob/c5be00b265e2e7e4646b07161ad955dba729409b/install_script.sh.template#L755-L762
PR introducing the `Unknown` entry: https://github.com/DataDog/agent-linux-install-script/pull/51/files#diff-79ac74a50e14d4fa9c80b1daba8bd5cc182f4b6c2a2b3951c0caa4fbc78f6f73. Previously, the hash did not have any defaults, so `nice_flavor` would end up empty:
```shell
flavor_to_readable=(
["datadog-agent"]="Datadog Agent"
["datadog-iot-agent"]="Datadog IoT Agent" …
```
> [bug] Fix exit condition if nice_flavor is unknown

- install_script.sh.template
We haven't published a public package of the fips-enabled flavor of the datadog agent yet but we need to add it as an option in the install script to allow the e2e test framework to run against it.
> [ASCII-2593] Add datadog-fips-agent to the linux install script hash as viable flavor

- install_script.sh.template
* https://www.shellcheck.net/wiki/SC2235: subshell overhead
* https://www.shellcheck.net/wiki/SC2002: useless cat, use `<` redirection
* https://www.shellcheck.net/wiki/SC2001: parameter expansion instead of sed
https://github.com/DataDog/agent-linux-install-script/actions/runs/12348751120/job/34458175806?pr=308 prevents from doing the release
> [chore] Shellcheck warning fix

- test/e2e/README.md
The example command in the README to run the e2e tests locally results in failing tests since it (1) doesn't specify the path to copy the scripts (2) doesn't indicate that the scripts have to be built and (3) doesn't have the API key set; provide a more complete example.
> [e2e] Correct example command in README

- test/e2e/common.go
Following https://github.com/DataDog/datadog-agent/pull/34489, the process-agent disables itself if it's not required to run. This leads to race conditions depending on the VM, if the process-agent exits before we check if it's alive.
This PR disables the process-agent check.
>  fix(tests): Disable process-agent live checks

- install_script.sh.template
- test/e2e/common.go
- test/e2e/go.mod
- test/e2e/go.sum
- test/e2e/install_error_tracking_standalone_test.go
Moving forward we'd like to make use of the `DD_CORE_AGENT_ENABLED` flag, which is why it's being written to the `/etc/environment`
This PR also fixes the error tracking standalone e2e test not being executed in the CI
> set environment variables for error tracking standalone

- .gitlab-ci.yml
- README.md
- install_script.sh.template
- test/e2e/install_discovery_test.go
- unit_tests/test_install_script.sh
Add support for enabling Service Discovery during installation by setting the `DD_DISCOVERY_ENABLED=true` environment variable. Note that Service Discovery needs system probe, so that configuration file is updated.
https://datadoghq.atlassian.net/browse/DSCVR-79
Unit tests and e2e tests have been added.
Manual test can be done with something like this:
On an EC2 instance or Linux VM:
```
make
DD_API_KEY=123 DD_SITE="datadoghq.com" DD_DISCOVERY_ENABLED=true ./install_script_agent7.sh
``` 
Once installation has finished, wait for the agent to start and then run:
```
sudo curl --unix-socket /opt/datadog-agent/run/sysprobe.sock http://unix/discovery/debug --fail-with-body
```
If the command does not fail, then Service Discovery has been enabled.
> Add option to enable Service Discovery

- install_script.sh.template
- test/e2e/install_installer_test.go
Downloads & uses the [installer install script](https://install.datad0g.com/scripts/install.sh) when using remote updates.
The installer install script must be pinned to the agent version and thus lives in the agent repository
> upgrade(installer): Use installer install script when DD_REMOTE_UPDATES=true

- install_script.sh.template
* Removes local version of `install_script_version` from the telemetry installer function
* The variable was added as a best practice in bash for safety (modifications to it are scoped to this function, stays stable within said function).
* However, there's no modification for said variable, no possible shadowing as the global `install_script_version` is never modified or re-instantiated by a different function, so we can ignore the argument above.
* Moreover, it breaks our `pre_release` task: https://github.com/DataDog/agent-linux-install-script/blob/3ec421b451b07b666fa092965033d784f23a6cae/Makefile#L71
* We could also modify our `sed` to instead avoid replacing `="$9"`
> Remove local `install_script_version` from `report_installer_telemetry`

- install_script.sh.template
- test/e2e/install_logs_config_process_collect_all_test.go
- unit_tests/test_install_script.sh
For process log collection, we want to have the agent logs to be excluded, so set the required option.
https://datadoghq.atlassian.net/browse/DSCVR-180
> Enable logs_config.process_exclude_agent for process logs

- install_script.sh.template
Today it's not possible to pin the APM SSI script; which means that we're enabling race conditions within the agent pipelines between publishing & E2E. This PR allows pinning to a specific pipeline ID.
> fix(ssi): allow script pinning for agent E2Es

- install_script.sh.template
There's a bad interaction where installing SSI creates `datadog.yaml`; which in turn prevents the rest of the install script from updating config.
To fix this, we move the SSI installation to the end of the script after configuration's been updated.
> fix(install_script): Fix security & SSI bad interactions

- .github/workflows/shellcheck.yml
- .github/workflows/slapr.yml
PR by [Bits](https://app.datadoghq.com/code?session_id=66989899-ff06-4dca-b66a-21ee43efd9c6) for [Dev Agent Session](https://app.datadoghq.com/code/7f40b736-e726-46ef-9efa-6454f4056ee9).
You can ask for changes by mentioning @Datadog in a comment.
Feedback (especially what can be better) welcome in [#code-gen-feedback](https://dd.enterprise.slack.com/archives/C07JA5N2D25)!
---
This PR pins GitHub Actions in our workflows to immutable commit SHAs to ensure reproducible and secure CI runs, while retaining the human-readable version as an inline comment.
Problem
- Workflows were referencing floating refs (e.g., v3, master), which can cause nondeterministic builds and may trigger policy/security checks that require SHA pinning.
Changes
- .github/workflows/shellcheck.yml
- actions/checkout …
> Pin GitHub Actions to commit SHAs with version comments

- README.md
- install_script.sh.template
- test/e2e/install_privileged_logs_test.go
- unit_tests/test_install_script.sh
Add an option to enable privileged logs in the system-probe configuration file. The feature is available [from agent 7.72](https://github.com/DataDog/datadog-agent/pull/38470).
https://datadoghq.atlassian.net/browse/DSCVR-193
> Add option to enable privileged logs
